const Game = require("./game");


const game1 = Game.newGame("Satish", "Nitish")
console.log(game1.play(3))
console.log("===============================")
console.log(game1.play(0))
console.log("===============================")
console.log(game1.play(1))
console.log("===============================")
console.log(game1.play(4))
console.log("===============================")
console.log(game1.play(5))
console.log("===============================")
console.log(game1.play(8))
console.log("===============================")
console.log(game1.play(6))
console.log("===============================")
console.log(game1.play(7))
console.log("===============================")
console.log(game1.play(8))
console.log("============Game 2=================")
let game2 = Game.newGame("Rohit", "Mohit")
console.log(game2.play(3))
console.log("===============================")
console.log(game2.play(0))
console.log("===============================")
console.log(game2.play(1))
console.log("===============================")
console.log(game2.play(2))
console.log("===============================")
console.log(game2.play(3))
console.log("===============================")
console.log(game2.play(4))
console.log("===============================")
console.log(game2.play(5))
console.log("===============================")
console.log(game2.play(6))
console.log("===============================")
console.log(game2.play(6))
console.log("===============================")
console.log(game2.play(7))
console.log("===============================")
console.log(game2.play(8))
console.log("===============================")
console.log(game2.play(8))

